# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: '2.0'
info:
  version: "1"
  title: tap-image-factory

  description: The Image Factory component is responsible for building Docker images based on application binaries or sources provided by the end-user.
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /healthz:
    get:
      summary: Get health status
      responses:
        200:
          description: OK
        500:
          description: Unexpected error
  /api/v1/image:
    post:
      summary: Build Image
      parameters:
        - name: body
          in: body
          required: true
          schema:
              $ref: "#/definitions/BuildImageRequest"
      responses:
        202:
          description: Image build process started
        400:
          description: Bad request. Provided wrong body.
          schema:
            type: string
        500:
          description: unexpected error
definitions:
  BuildImageRequest:
    type: object
    required:
      - id
    properties:
      id:
        type: string
